### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by Scott-Young-6746** [michaelbull/kotlin-result#1]
Copying the following lines:

 `maven { url "https://jitpack.io" }`
`compile 'com.github.michaelbull:kotlin-result:1.1.0'`

into the `repositories` and `dependencies` respectively generated a build error in Gradle.

Build error is as follows:
Warning:<i><b>root project 'my_project': Unable to build Kotlin project configuration</b>
Details: java.lang.reflect.InvocationTargetException: null
Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':compileClasspath'.
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.github.michaelbull:kotlin-result:1.1.0.
Searched in the following locations:
    https://repo1.maven.org/maven2/com/github/michaelbull/kotlin-result/1.1.0/kotlin-result-1.1.0.pom
    https://repo1.maven.org/maven2/com/github/michaelbull/kotlin-result/1.1.0/kotlin-result-1.1.0.jar
    https://jitpack.io/com/github/michaelbull/kotlin-result/1.1.0/kotlin-result-1.1.0.pom
    https://jitpack.io/com/github/michaelbull/kotlin-result/1.1.0/kotlin-result-1.1.0.jar
Required by:
    project :</i>

**Comment by michaelbull** [comment]
Typo in the README, should be version `1.0.0`. Will fix, thanks.
