### ISSUE TITLE
How to use the new inlined Result in non-Kotlin code?

### ISSUE THREAD

**Issue by efenderbosch-atg** [michaelbull/kotlin-result#101]
Our tests are written in Groovy using the Spock framework.

Previously, we could do something like this:

```groovy
when:
Result<InputStream, S3FileService.Failure> result = service.s3Download(request)

then:
Ok<InputStream> ok = result as Ok<InputStream>
Object value = ok.value
InputStream inputStreamResponse = value as InputStream
assert inputStreamResponse.readAllBytes() == responseBytes
```

Now, we can't even call the `s3Download` function from Groovy. All three of these:

```groovy
Result<InputStream, S3FileService.Failure> result = service.s3Download(request)
//
InputStream result = service.s3Download(request)
//
Object result = service.s3Download(request)
//
```
throw `groovy.lang.MissingMethodException`

Is there any way to use the new value class Result outside of Kotlin?

Maybe Result could implement some interface with `value()` and `err()` functions then Java/Groovy code can just treat it as the interface?

https://stackoverflow.com/questions/77583417/how-to-use-kotlin-value-class-from-java-code

**Comment by michaelbull** [comment]
Could you post the full stacktrace? This seems fundamentally like a problem with Groovy's compiler - under the hood an inline class disappears, so when you're using it with other JVM languages other than Kotlin (which this library is not designed for) I suspect their compilers don't understand the fact that the type disappears.

One suggestion could be to test `service.s3download(request).unwrap()` (see: [`unwrap`](https://github.com/michaelbull/kotlin-result/blob/3a50dfa69dede13b59365e14f8efdf89df175fe0/kotlin-result/src/commonMain/kotlin/com/github/michaelbull/result/Unwrap.kt#L16)). I'm not sure if you'll need to make a Kotlin function that calls this and then make your Groovy code call that, but at that point the return type of that function will be the underlying `InputStream` and it will `throw UnwrapException`  if it failed, which would also therefore fail your test.

It's worth mentioning that this library is taking full advantage of a stable Kotlin feature for Kotlin developers on Kotlin projects - I wouldn't really advise writing code that exposes this type as part of a public API to consumers that aren't also in Kotlin (which your tests, as a consumer, are not). Interoperability across other languages is a non-goal outside of what Kotlin itself promises to support.

**Comment by michaelbull** [comment]
Just done a bit more of a dig - I think the issue is that if you return a `Result` then your function name will be mangled during compilation. According to [the docs](https://kotlinlang.org/docs/inline-classes.html#calling-from-java-code) you can avoid this by annotation your function with `@JvmName("yourName")` which will be the stable identity for the function - whatever you put in the annotation is what you will need to write when you call it from Groovy. Probably a good idea to keep it the same as the function name.

Perhaps give that annotation a go, and if not try the example I posted above. Let me know how you get on.

**Comment by efenderbosch-atg** [comment]
I'll have to do some digging. It doesn't like that. Maybe since it is a return value instead of function argument?

`AuthenticationService.kt:35:5 '@JvmName' annotation is not applicable to this declaration`

```kotlin
@JvmName("authenticate")
fun authenticate(request: AuthRequest): Result<Token, Failure> { ... }
```
Kotlin 1.9.22 targeting Java 21

**Comment by michaelbull** [comment]
I've confirmed that it works for me on a function declaration with `Result` as a return type. I did this by adding the `@JvmName` annotation, recompiling, and decompiling the output `.class` with [cr](https://www.benf.org/other/cfr/), below is what I got.

Before:

```java
    @NotNull
    public final Object checkSlot-Zyo9ksc(@NotNull Obj obj) {
        ....
    }
```

After:


```java
    @JvmName(name="checkSlot")
    @NotNull
    public final Object checkSlot(@NotNull Obj obj) {
       ...
    }
```

**Comment by efenderbosch-atg** [comment]
Which Kotlin version and Java version? I wonder why it won't compile for me.


This seem to work, which means I can probably add a method using Groovy's meta programming to attempt to find the non-mangled name.

```groovy
class AuthenticationServiceSpec extends Specification {

    static {
        AuthenticationService.metaClass.authenticate = { AuthRequest r -> 'authenticate-Zyo9ksc'(r) }
    }

  // tests...
}
```

**Comment by efenderbosch-atg** [comment]
That worked.

```groovy
    def "test user not found"() {
        given:
        SecurityUserEntity user = SecurityFixtures.securityUserEntity()
        AuthRequest request = new AuthRequest(user.username, user.password)

        and:
        authenticationManager.authenticate(_ as Authentication) >> { throw new UsernameNotFoundException('testing') }

        when:
        Object failure = service.authenticate(request)

        then:
        // noinspection GrUnresolvedAccess
        failure.error instanceof AuthenticationService.Failure.Authentication
    }
```
The return can't be strongly typed and I need to ignore that it doesn't recognize the `error` method.

**Comment by michaelbull** [comment]
No problem.

**Comment by efenderbosch-atg** [comment]
BTW, I think I figured out why I needed `@Suppress("INAPPLICABLE_JVM_NAME")` and you didn't. We have the Kotlin Spring plugin enabled, which, by default, makes all classes with certain annotations open. In this case the services are tagged w/ `@Transactional`. `@JvmName` annotation is not allowed for overridden or overridable functions.
