### ISSUE TITLE
Question: Creating an instance of Result<V, E> in Swift

### ISSUE THREAD

**Issue by curioustechizen** [michaelbull/kotlin-result#108]
I've been using `Result<V, E>` for quite some time in a KMP project targeting Android and iOS. I've successfully _consumed_ instances of Result from Swift. It is not pretty and results in some loss of safety but it works.

Now I have a situation where I want to _produce_ an instance of Result from Swift. Are there examples on how to go about doing this?

**Comment by michaelbull** [comment]
Creating a Result is achieved by calling the Ok/Err functions.

Some initial Googling of calling Kotlin code in Swift returns [this article](https://kotlinlang.org/docs/native-objc-interop.html) and [this example repo](https://github.com/kotlin-hands-on/kotlin-swift-interopedia) which has interoperability examples.

Hope that helps.

**Comment by curioustechizen** [comment]
Sorry somehow this notification slipped through my fingers.

I'm aware of the basics of calling Kotlin code from Swift. The problem was more related to how to make the `Ok()` and `Err()` constructors visible from the Swift side, especially if kotlin-result is a transitive dependency and not visible to the Swift side directly.

For now I refactored my code to avoid having to create instances of kotlin-result on the Swift side. However if I end up having more situations that require this then I will revisit and post a follow up here.

**Comment by sayah-y** [comment]
@curioustechizen please take a look to the following issue:
https://github.com/michaelbull/kotlin-result/issues/109
