### ISSUE TITLE
Question: is runCatching the equivalent to F#'s result "computational expression"?

### ISSUE THREAD

**Issue by mbucc** [michaelbull/kotlin-result#11]
Example computational expression from Scott Wlaschin's book:

https://github.com/swlaschin/DomainModelingMadeFunctional/blob/master/src/OrderTakingEvolved/PlaceOrder.Dto.fs#L71-L81

The alternative (adding more versions of zip with more and more arguments) smells wrong.  I noticed in your example service code you use runCatching in a very similar way to the code linked above.

**Comment by michaelbull** [comment]
I'm not familiar with F# so I don't really understnad what's going on in the code linked

**Comment by mbucc** [comment]
I'm back to my previous question on using unwrap.  :)

I'm not an F# user either, but if I think I understand the explanation SW gives in his book, which is:

```
// A result computational expression:
result {
   // checkAddress returns a Result<Address, Msg>
   // but x1 is of type Address.
   let! x1 = checkAddress unvalidatedAddress
   let! x2 = checkName unvalidatedName
   return ValidatedAddress(x1, x2)
}   // Type of this full expression is Result<ValidatedAddress, Msg>
```

The closest match I can think of with kotlin-result is unwrap() on each line, all surrounded by runCatching.  I know in a previous issue, you suggested not using unwrap() in this way, but I can't think of another way (other than continuing to expand zip).

**Comment by michaelbull** [comment]
Maybe [this](https://github.com/michaelbull/kotlin-result/issues/9#issuecomment-573368330) comment helps?

**Comment by Munzey** [comment]
@mbucc just read this and your previous issue. I believe the exact thing you are looking for is called a [monad comprehension](https://arrow-kt.io/docs/0.10/patterns/monad_comprehensions/).
I have opened a pr to add the functionality you are looking for:
https://github.com/michaelbull/kotlin-result/pull/13
