### ISSUE TITLE
Kotlin doesn't support exporting inline classes to Objective-C/Swift, making Result 2.x a no-go for APIs consumed in iOS

### ISSUE THREAD

**Issue by tiwoc** [michaelbull/kotlin-result#110]
The Kotlin compiler doesn't support exporting inline classes to Objective-C/Swift ([docs](https://kotlinlang.org/docs/native-objc-interop.html#unsupported), [Interopedia](https://github.com/kotlin-hands-on/kotlin-swift-interopedia/blob/main/docs/classesandinterfaces/Inline%20classes.md)), which Result 2.x is built upon. Instead of representing the result type in the headers, the compiler will use `id` (Objective-C) which translates to `Any` on the Swift side, meaning that it's impossible to get the value or error encapsulated in the result on the Swift side.

We're currently using Result 1.x to return results from shared Kotlin code to the native client apps on all platforms. I'm not sure there's anything that can be done on the Result end (short of moving away from inline classes again), but I wanted to call out that it's impossible for teams using Result in the API of their multiplatform library to upgrade to 2.x at the moment. A warning in the readme that 2.x can't be used in APIs exported to iOS might be very helpful for teams considering whether to adopt the library for their multiplatform project or not.

I understand the [reasons](https://github.com/michaelbull/kotlin-result/wiki/Overhead) why using inline classes is superior for the happy path, so please know that I don't want to put any blame on you.

### Example

Kotlin code (slightly edited sample code from the KMP wizard):
```kotlin
fun greet(): Result<String, Nothing> {
    return Ok("Hello, ${platform.name}!")
}
```

Generated Objective-C header file with Result 1.1.21:
```objc
- (SharedKotlin_resultResult<NSString *, SharedKotlinNothing *> *)greet __attribute__((swift_name("greet()")));
```

Generated Objective-C header file with Result 2.0.0:
```objc
- (id _Nullable)greet __attribute__((swift_name("greet()")));
```

**Comment by michaelbull** [comment]
@tiwoc I've closed it as it's not the responsibility of this library to solve. It's a problem with the use of the Kotlin multiplatform plugin and inline values with the Kotlin compiler. Both of those issues concern issues that should be opened on [Kotlin's own issue tracker](https://youtrack.jetbrains.com/issues/KT). It can't be solved by anything we're doing, so it needs to be solved by the Kotlin team.

**Comment by michaelbull** [comment]
If you have a link to an issue that you’ve reported to the Kotlin team that outlines the problem they need to fix I am happy to direct traffic towards it.As I have said multiple times now, I will not be adding a disclaimer to the README of the project painting it in a negative light on the back of problems that (a) it does not introduce, (b) it is not responsible for fixing, (c) are not unique to this project. Please stop asking.If you want this problem fixed, you need to put pressure on the Kotlin team to fix it.> about the unsupported inline classes used by this libraryThis library does not use “unsupported inline classes”. Inline classes have been a stable kotlin language feature for almost 4 years and the library uses them whilst targeting all 3 tiers of native support.If there is a platform specific problem with the code emitted by the kotlin compiler then it is a kotlin compiler bug.On 17 Dec 2024, at 09:38, LukasVykuka ***@***.***> wrote:﻿
A short, friendly reminder in the README about the unsupported inline classes used by this library can be very helpful and time-saving when researching which solution or library to use for KMP.

**Comment by robertvoigt030** [comment]
> If you have a link to an issue that you’ve reported to the Kotlin team that outlines the problem they need to fix I am happy to direct traffic towards it.

There you go

https://youtrack.jetbrains.com/issue/KT-32352/inline-classes-are-exported-as-id-to-objc-swift

**Comment by michaelbull** [comment]
Feel free to open a PR that adds an explanation and directs conversation to that link.
