### ISSUE TITLE
Request: new 1.x release with un-deprecated APIs

### ISSUE THREAD

**Issue by GrahamBorland** [michaelbull/kotlin-result#115]
@michaelbull Because of #110 we are locked to v1.x of this library. Would you consider publishing a new 1.x build which removes the `@Deprecated` warnings on `OK` and `Err`? If we're happy using 1.1.21, which we are, it would be nice not to have to suppress that warning everywhere we use those APIs.

We can't downgrade to 1.1.20, pre-deprecation, because we're using some of the newer features in 1.1.21.

**Comment by michaelbull** [comment]
No reply - closed.
