### ISSUE TITLE
Provide `mapSuspendCatching` ?

### ISSUE THREAD

**Issue by kdarrimajoupro** [michaelbull/kotlin-result#117]
Hello ! 
It would be a good idea to provide a `mapSuspendCatching` : 

```kotlin
public inline infix fun <V, U> Result<V, Throwable>.mapSuspendCatching(transform: (V) -> U): Result<U, Throwable> {
    contract {
        callsInPlace(transform, InvocationKind.AT_MOST_ONCE)
    }

    return when {
        isOk -> runCatching { transform(value) }.throwIf {  it is CancellationException }
        else -> this.asErr()
    }
}
```

What do you think ?

**Comment by michaelbull** [comment]
https://github.com/michaelbull/kotlin-result/blob/aa0c0ac53ac89fadc157d29a41ca29edf8bf39e2/kotlin-result-coroutines/src/commonMain/kotlin/com/github/michaelbull/result/coroutines/RunSuspendCatching.kt#L34

**Comment by kdarrimajoupro** [comment]
If I need to chain 2 suspended calls, I am not sure your solution to use a `map` will work :

```kotlin
runSuspendCatching { apiClient.getToken() }
            .map { dataStore.save(it) }
```

That's why I have suggested `mapSuspendCatching`. But I could do it like that :

```kotlin
runSuspendCatching { 
    val token = apiClient.getToken()
    dataStore.save(token)
}
```

**Comment by kdarrimajoupro** [comment]
Yes, you are right !

Thanks for the talk !
