### ISSUE TITLE
flatMap

### ISSUE THREAD

**Issue by Ravirael** [michaelbull/kotlin-result#2]
I can't see a `flatMap` function or its equivalent which is typical for monads. It should work like Haskell's `>>=`.  

My suggested implementation:
```
infix inline fun <V, E, U> Result<V, E>.flatMap(transform: (V) -> Result<U, E>) : Result<U, E> {
    return when (this) {
        is Ok -> transform(value)
        is Err -> this
    }
}
```
Also `flatMapError` function could be implemented in simillar way. If you like the idea, I will implement them along with unit tests and create a pull request.

Thanks!

**Comment by michaelbull** [comment]
Do you mean [andThen](https://github.com/michaelbull/kotlin-result/blob/master/src/main/kotlin/com/github/michaelbull/result/And.kt#L23)?

**Comment by Ravirael** [comment]
Yes, that's it. Thank you!

**Comment by michaelbull** [comment]
I don't see how that's semantically a `flatMap`, when you look at Kotlin's definition of a `flatMap` (applies a function to every element of a map, returning a single list of the elements). The naming `andThen` comes from Elm's [`andThen`](http://package.elm-lang.org/packages/elm-lang/core/latest/Result#andThen).

**Comment by Ravirael** [comment]
You mention the extension function for Kotlin's `Map`class. However there is also a version for `Iterable` with signature `fun <T, R> Iterable<T>.flatMap(transform: (T) -> Iterable<R>): List<R> `. As you can see this is really similar to your `andThen` by parameters and return type. Both functions are defined for some `Monad<T>` take function `(T) -> Monad<R>` and return `Monad<R>`, that's why this name seems reasonable for me. 

Also in [this](https://github.com/danneu/kotlin-result) alternative library that operation is called `flatMap`.

Of course using Elm's convention also makes sense.

**Comment by michaelbull** [comment]
The `flatMap` on an `Iterable<T>` conforms to Kotlin's definition of `flatMap` as it returns a single `List<R>` of elements yielded from the results of the `transform` function being applied to each element (`T`) in the `Iterable<T>`. The signature for `andThen` doesn't operate on an `Iterable` nor a `Map` - and does not yield a `List` of `Result`s, just a single `Result`. I think the naming in that library is misleading.

**Comment by Ravirael** [comment]
Well, there also is a [`flatMap`](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#flatMap-java.util.function.Function-) method in Java's `Optional` and similary `flatMap` in Scala's [`Option'](https://www.scala-lang.org/api/current/scala/Option.html). They are equivalent to your `andThen` as much as they can be!

**Comment by michaelbull** [comment]
I think that's a stronger argument, however I still feel uneasy given Kotlin's use of `flatMap`. Happy to consider adding `flatMap` as an alias of `andThen` on the back of this if people think it's necessary.

**Comment by kevinherron** [comment]
FWIW, I also scratched my head looking for the missing `flatMap` function.

I think it's okay for `flatMap` to have a slightly different definition when applied to an Iterable or Collection as when applied to something like Result (or Either, or Option, etc...).

It's the same way in Scala land.

**Comment by michaelbull** [comment]
Does Scala have a Result type with `flatMap` on it? I'm under the impression that its existence on the `Optional` class is due to the fact that `Optional` can be argued as a unary "collection", which is much harder to argue for in the Result class.

Not to mention other functional languages have opted for `andThen` as their naming scheme for this method:

- Rust: [Result.and_then](https://doc.rust-lang.org/std/result/enum.Result.html#method.and_then)
- Elm: [Result.andThen](http://package.elm-lang.org/packages/elm-lang/core/latest/Result#andThen)

**Comment by kevinherron** [comment]
It has `Either`, which is basically the same thing (except it's right-biased, whereas your Result is left-biased because it names the left and right as value/error). 

I'm not disputing `andThen` as an inappropriate name, but this operation is fundamentally `flatMap`.

**Comment by michaelbull** [comment]
On the back of `flatMap` existing on Scala's `Either`, I've added an alias function named `andThen` to `Map.kt` (44a4467595a0ade41a47bdfffe7f934eded0a2d9).

**Comment by stefanusayudha** [comment]
how in the world we would know "andThen". i think we need to stop adding unnecessary semantic. and design the language based on the theory to avoid mind mapping. kotlin do it good so far but why there is no Result.flatMap
