### ISSUE TITLE
[QUESTION] Is binding available on 1.1.6?

### ISSUE THREAD

**Issue by Sottti** [michaelbull/kotlin-result#21]
I can't seem to find `binding` even when is available as documentation on the front page. Is it available on 1.1.6?

Thanks

**Comment by michaelbull** [comment]
The documentation in the README represents the in-development 1.1.7 release.

The commit to add the `binding` function came in after [1.1.6](https://github.com/michaelbull/kotlin-result/compare/1.1.6...master). Maven central seems to be having connection issues every time I try and publish 1.1.7, so I need to contact them about why I can't publish to the coordinates whenever I have time.

**Comment by Sottti** [comment]
Thanks!

**Comment by michaelbull** [comment]
This functionality is now released as part of [1.1.7](https://github.com/michaelbull/kotlin-result/releases/tag/1.1.7)
