### ISSUE TITLE
runCatching catches Throwable?

### ISSUE THREAD

**Issue by lawkai** [michaelbull/kotlin-result#22]
Hi, in Java, it is generally consider a bad practice to catch Throwable instead of Exception due to Throwable being the super class of Error which represents lower level errors like OutOfMemory etc. 
May I know is there any reason why runCatching is catching Throwable instead of Exception?

**Comment by michaelbull** [comment]
Because that's what Kotlin's own `Result` type (which came after this library and is far more limited than this library) does.

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/run-catching.html#runcatching

> Calls the specified function block and returns its encapsulated result if invocation was successful, catching any Throwable exception that was thrown from the block function execution and encapsulating it as a failure.
