### ISSUE TITLE
Can't find artifact

### ISSUE THREAD

**Issue by tmohme** [michaelbull/kotlin-result#26]
First of all, thanks for the great work!

As far as I understand I should be able to find the current version (`com.michael-bull.kotlin-result:kotlin-result:1.1.8`) at maven central.
Unfortunately when looking there I only find the POM and checksum files, but not the JAR. Same for `1.1.7`.
Only for `1.1.6` I'm able to find the actual JAR on mane central.

Is this a misunderstanding from my side or where can I find the current JAR?

**Comment by michaelbull** [comment]
I think you're looking for https://repo1.maven.org/maven2/com/michael-bull/kotlin-result/kotlin-result-jvm/1.1.8/

**Comment by tmohme** [comment]
Nailed it!

Thx again!

**Comment by michaelbull** [comment]
:+1: no worries
