### ISSUE TITLE
Mapping a failure to success 

### ISSUE THREAD

**Issue by badvok666** [michaelbull/kotlin-result#30]
This is probably not an issue. Its more of a query i have. I very well could be misusing, misunderstanding or not aware of something. 

The use case is if the api call fails i want it to successfully return the cache. 

Much like andThen allows the transforming of one thing to another contained withing the Result type. What i feel i am looking for is a way to "andThen the error". So i can transform the E into a success using Ok(SomeType)

I can't find the function though i could just be using it wrong/this is not the correct practice. 
For now i'm letting my Error contain any type so it can optionally return the result i want. 

Thanks in advance, really loving using kotlin-result so far.

**Comment by michaelbull** [comment]
I think you want [`recover`](https://github.com/michaelbull/kotlin-result/blob/bca344daafadbc7af42089b88c712ac1061298dd/src/commonMain/kotlin/com/github/michaelbull/result/Or.kt#L44)

It would go something like:

```kotlin
class Good( ... )
class Bad(... )

fun makeCall() : Result<Good, Bad> = { ... }

fun caller() {
   val result: Ok<Good> = makeCall().recover { error -> Good(...)  }
}
```

**Comment by badvok666** [comment]
I think that it is. 

Thanks!!, Totally loving this and am in the process of replacing sealed classes. I do not miss the in-lining of the when()s

**Comment by michaelbull** [comment]
:+1: let me know if you need help getting unblocked again.
