### ISSUE TITLE
Mapping a failure to success given a predicate

### ISSUE THREAD

**Issue by oddsund** [michaelbull/kotlin-result#39]
While wrapping calls to an external api, one pattern emerged - recoverIf. So it would be similar to `toErrorIf`  and `toErrorUnless`, and would allow us to selectivly recover from known errors.

Is there any reason that this is not implemented? If not, I'll try to provide a PR during the weekend.

**Comment by michaelbull** [comment]
Sounds like a good idea, would be willing to accept a PR for this 👍
