### ISSUE TITLE
Are there plans for a website for documenting functionality?

### ISSUE THREAD

**Issue by shalbert94** [michaelbull/kotlin-result#43]
Due to the heavy usage of extension functions, it's difficult to find this library's functionality by looking through source code in the IDE. Look through the source code on Github is seemingly the best option for now

**Comment by michaelbull** [comment]
Right now there are no plans for an external website. We have the [wiki](https://github.com/michaelbull/kotlin-result/wiki) which does go quite a long way in documenting the functions.

I wouldn't be opposed to a website though, provided the src was in the same repository. I suppose GitHub pages could be a solution?

**Comment by shalbert94** [comment]
Thank you for sharing the wiki, I should have checked earlier. 

As a person with no knowledge of Elm, Rust, Haskell, or Scala the wiki is difficult to digest. Are you open to organizing it differently? Such as split it into `Return` and `Either`?

**Comment by michaelbull** [comment]
I'm open to adding more pages to the Wiki. The current structure is ideal for those who have had experience with the Return type that exists in other languages and that's the audience it was designed for, but we can always add more pages

**Comment by shalbert94** [comment]
Doesn't seem like there's a way for me to contribute to the wiki. Is that an incorrect understanding?

**Comment by michaelbull** [comment]
Looks like that's a [GitHub limitation](https://github.community/t/how-to-fork-a-wiki-and-send-a-pr/2006).

If you propose changes as markdown in this issue I'll go ahead and apply them manually.

**Comment by shalbert94** [comment]
I Will try to put up a PR next week
