### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by breucode** [michaelbull/kotlin-result#45]
First of all, thanks for the nice result library you provide!

I would like to use the recoverIf function, which was introduced in one of the last PRs.

Is there a release due in the near future?

**Comment by michaelbull** [comment]
Hi @breucode, I will try to produce a release this weekend, cheers

**Comment by michaelbull** [comment]
Hi @breucode, [1.1.10](https://github.com/michaelbull/kotlin-result/releases/tag/1.1.10) is now available. Furthermore, SNAPSHOT releases will be automatically published and available [here](https://oss.sonatype.org/content/repositories/snapshots/com/michael-bull/kotlin-result/kotlin-result/) going forward should you find a piece of functionality in development that isn't yet released.
