### ISSUE TITLE
Move coroutine tests to use kotlinx-coroutines-test instead of runBlockingTest

### ISSUE THREAD

**Issue by Munzey** [michaelbull/kotlin-result#50]
See Roman's latest comment: https://youtrack.jetbrains.com/issue/KT-22228#focus=Comments-27-4791713.0-0

**Comment by michaelbull** [comment]
Also may be relevant: https://blog.jetbrains.com/kotlin/2021/04/kotlin-1-5-0-rc-released/#test-library-changes

**Comment by michaelbull** [comment]
For some reason, the `kotlinx-coroutines-test` library depends on the JVM implementation of kotlin-coroutines, so it isn't cross-platform and thus can't replace the `runBlockingTest` in this library.

**Comment by michaelbull** [comment]
Going to close this issue until https://github.com/Kotlin/kotlinx.coroutines/issues/1996 is resolved.
