### ISSUE TITLE
Problem with using kotlin-result via maven

### ISSUE THREAD

**Issue by filipamb** [michaelbull/kotlin-result#51]
Hello

I am trying to add kotlin-result to my maven project, however strange things starts to happen then. After adding
```xml
<dependency>
  <groupId>com.michael-bull.kotlin-result</groupId>
  <artifactId>kotlin-result</artifactId>
  <version>1.1.11</version>
</dependency>
```
Dependency is added, jar is downloaded , however I cannot import any class - maven just doesn't see classes from **com.github.michaelbull** package.

My properties for kotlin and java are:
```xml
<java.version>11</java.version>
<kotlin.version>1.4.31</kotlin.version>
```

Do you know what can cause such problems? I have never had such problem with any other library.

**Comment by michaelbull** [comment]
Can you provide a log of the maven command you're running in which it fails to resolve anything from that package? Failing that a reproducible test case would also help.

**Comment by filipamb** [comment]
@michaelbull thx for quick response! I have just created repo from spring initializer using maven and kotlin
https://github.com/filipamb/kotlin-result-maven/blob/master/pom.xml

Here is class where I am trying to import Result
https://github.com/filipamb/kotlin-result-maven/blob/master/src/main/kotlin/com/example/demo/TestClass.kt

**Comment by michaelbull** [comment]
It seems the problem is that Maven doesn't know what environment you're trying to build for the same way Gradle does, so you'll have to explicitly depend on whichever platform version you want. For it to resolve the JVM artifacts properly I used this:

```xml
		<dependency>
			<groupId>com.michael-bull.kotlin-result</groupId>
			<artifactId>kotlin-result-jvm</artifactId>
			<version>1.1.11</version>
		</dependency>
```

**Comment by michaelbull** [comment]
@filipamb did the above comment resolve your issue?

**Comment by filipamb** [comment]
Ye, helped. Thanks!

**Comment by mguelton** [comment]
Hello,

May be the README sould be updated with a Maven Installation section containing the dependency above. I have run into the same issue.
