### ISSUE TITLE
Missing kotlin-result-mingwx64 on maven

### ISSUE THREAD

**Issue by terahlunah** [michaelbull/kotlin-result#52]
Hello, I'm trying to build a KMP lib but I can't build the native variant (I've been able to build the other variants fine)

```
Execution failed for task ':compileKotlinNative'.
> Could not resolve all files for configuration ':nativeCompileKlibraries'.
   > Could not resolve com.michael-bull.kotlin-result:kotlin-result:1.1.11.
     Required by:
         project :
      > No matching variant of com.michael-bull.kotlin-result:kotlin-result:1.1.11 was found.
      ...
```

From what I understand, the mingwx64 variant of kotling-result seems to be missing for maven 
https://search.maven.org/search?q=g:com.michael-bull.kotlin-result

Do you plan to add the mingwx64 artifact on maven in the future ?

**Comment by michaelbull** [comment]
Hi. We introduced new cross-platform build targets in c4c70b4d984c96693fe49ad5fa25035a6d99c965,, but haven't had time to create a new release yet. However, you can still access these artifacts if you're comfortable using the [snapshot release](https://oss.sonatype.org/content/repositories/snapshots/com/michael-bull/kotlin-result/kotlin-result-coroutines-mingwx64/).

**Comment by terahlunah** [comment]
I'm fine with using the snapshot release, thank you very much for the help!
