### ISSUE TITLE
Implement method into_ok_or_err for Result<T, T>

### ISSUE THREAD

**Issue by olback** [michaelbull/kotlin-result#58]
I think it'd be nice to be able to write something like
```kotlin
val a = res.map { it.joinToString("\n") }.into_ok_or_err()
```
instead of
```kotlin
val a = when (res) {
    is Ok -> res.unwrap().joinToString("\n") // -> String
    is Err -> res.unwrapError() // -> String
}
``` 

This feature already exists in [Rust Nightly](https://doc.rust-lang.org/std/result/enum.Result.html#method.into_ok_or_err).

**Comment by michaelbull** [comment]
Can you describe the receiver type and the return type more precisely? Struggling to understand what this is meant to take and produce with the implicit type in your examples

**Comment by olback** [comment]
Yes, sorry.

```kotlin
val res: Result<List<String>, String> = fetchList()
val output: String = res.map { it.joinToString("\n") }.into_ok_or_err()
```
Another example:
```kotlin
val res: Result<String, String> = fetchString()
val output: String = res.into_ok_or_err()
```
Essentially just takes the ok value if ok and err value if not ok.

**Comment by michaelbull** [comment]
Does this differ from [merge](https://github.com/michaelbull/kotlin-result/blob/master/kotlin-result/src/commonMain/kotlin/com/github/michaelbull/result/Get.kt#L130)?

**Comment by olback** [comment]
Nope, I just totally missed that method.

Thank you!

**Comment by michaelbull** [comment]
No worries, here's the [wiki entry](https://github.com/michaelbull/kotlin-result/wiki/Scala#mergeableeithermerge) for it if that helps.
