### ISSUE TITLE
Master doesn't compile in local

### ISSUE THREAD

**Issue by pablisco** [michaelbull/kotlin-result#60]
I was trying to build the project but it looks like I may be missing some settings and fails when trying to evaluate Gradle:

https://scans.gradle.com/s/3s5ii623zjtck/failure#1

**Comment by michaelbull** [comment]
```org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'kotlinx.benchmark', version: '0.2.0-dev-20', apply: false] was not found in any of the following sources:	```

Seems like the dev version of the benchmark plugin has been removed from one of the remote repositories. I suspect using a newer version, ideally not one marked with `dev`, will solve the problem

**Comment by michaelbull** [comment]
Addressed in https://github.com/michaelbull/kotlin-result/pull/61
