### ISSUE TITLE
Assertion helpers for tests

### ISSUE THREAD

**Issue by ashughes** [michaelbull/kotlin-result#74]
Would you be open to adding helper functions for using `Result`s in tests?

For example:
```kotlin
inline fun <reified V, reified E> Result<V, E>.assertOk(): V {
    assertIs<Ok<V>>(this)
    return value
}
```

Usage:
```kotlin
fun doSomething(): Result<String, Exception> {
    // ...
}

@Test
fun test() {
    val success: String = doSomething().assertOk()
}
```

**Comment by michaelbull** [comment]
I suppose this could live in a `kotlin-result-test` package or similar, which has a dependecy on the multiplatform `kotlin.test` package and also exports the functions as described in your post. What I would like to avoid is forcing people who use the core library to consume the `kotlin.test` library in their runtime code, instead they would do something like `dependencies { testImplementation('...:kotlin-result-test:..') }`

**Comment by curioustechizen** [comment]
I use slightly modified versions of the proposed functions:

```kt
inline fun <V, E> Result<V, E>.assertOk(assertion: (value: V) -> Unit) {
    try {
        assertion.invoke(this.expect { "Expected the result to be an Ok, found an Err instead" })
    } catch (e: UnwrapException) {
        fail(e.message)
    }
}

inline fun <V, E> Result<V, E>.assertErr(assertion: (err: E) -> Unit) {
    try {
        assertion.invoke(this.expectError { "Expected the result to be an Err, found an Ok instead" })
    } catch (e: UnwrapException) {
        fail(e.message)
    }
}
```

Usage:

```kt
fun doSomething(): Result<String, Exception> {
    // ...
}

@Test
fun test() {
    doSomething().assertOk { assertEquals("expected", it) } 
}
```

I find that in majority of the cases the assertion ends up being `assertEquals` so there might be merit in introducing a shortcut for that case:

```kt
inline fun <V, E> Result<V, E>.assertOkEquals(expected: V) {
    try {
        assertEquals(expected, this.expect { "Expected the result to be an Ok, found an Err instead" })
    } catch (e: UnwrapException) {
        fail(e.message)
    }
}
```

**Comment by michaelbull** [comment]
Closing this for now unless there is significant demand for it. General advice would be to follow how the unit tests in the library itself are written, e.g. 

```kotlin
fun someComputation(): Result<Int, ComputeError>

val expected = Ok(50)
val actual = someComputation()

assertEquals(expected, actual)
```
