### ISSUE TITLE
Feature request: mingwX86 target

### ISSUE THREAD

**Issue by JohnLCaron** [michaelbull/kotlin-result#77]
Would it be possible/easy to add target mingwX86?

PS: thanks for such an elegant design.

**Comment by michaelbull** [comment]
Kotlin Coroutines [doesn't support mingw86](https://github.com/Kotlin/kotlinx.coroutines/issues/2157), so probably not.

**Comment by 05nelsonm** [comment]
The `kotlin-result-coroutine` module is limited, yes, but it is doable for the `kotlin-result` module since it's only dependency is the standard library.

I would love to see this as well, but for **all** available targets (not just `mingwx86`) so that I can use it in my library's public APIs.
