### ISSUE TITLE
About component1() and 2

### ISSUE THREAD

**Issue by caiofaustino** [michaelbull/kotlin-result#79]
Hi,

I was looking at the code and it seems that the [`component1()`](https://github.com/michaelbull/kotlin-result/blob/master/kotlin-result/src/commonMain/kotlin/com/github/michaelbull/result/Result.kt#L12) and `component2()` methods in the `Result` class are not really used anywhere.

I was wondering if they have any use that I'm failing to see here or if they could be removed.

Thanks.

**Comment by michaelbull** [comment]
```kotlin
fun exampleFunction(): Result<Int, SomeErr> = { ... }

val (number, error) = exampleFunction()
```

**Comment by caiofaustino** [comment]
Thanks a lot for the explanation!
