### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by mbucc** [michaelbull/kotlin-result#8]
I think you mean:

`UnwrapException("called Result.unwrap on an Err value $error")`

instead of

`UnwrapException("called Result.wrap on an Err value $error")`

https://github.com/michaelbull/kotlin-result/blob/6651b18905feebdbc445741168ee7128e18c5b5e/src/main/kotlin/com/github/michaelbull/result/Unwrap.kt#L22

**Comment by michaelbull** [comment]
Good spot! Fixed.

**Comment by michaelbull** [comment]
Release 1.1.5 is out with this fix in.
