### ISSUE TITLE
ensureNotNull-alike binding scope extensions

### ISSUE THREAD

**Issue by kirillzh** [michaelbull/kotlin-result#84]
Arrow has a handy extension for eagerly returning from effect with an error if a value is null - [`ensureNotNull`](https://arrow-kt.io/docs/apidocs/arrow-core/arrow.core.continuations/ensure-not-null.html). Would be very helpful to have a similar extension here, right now need to rely on fairly nested `flatMap`:

```kotlin
val value = maybeGetValue()
  .flatMap {
    when (it) {
      null -> Err(ValueMissingError)
      else -> Ok(it)
    }
  }
  .bind()
```

vs 

```kotlin
val value = maybeGetValue().bind()
ensureNotNull(value) { ValueMissingError }
```

**Comment by michaelbull** [comment]
I may be misunderstanding, but I think we already support this behaviour with [`toResultOr`](https://github.com/michaelbull/kotlin-result/blob/ce6131be3de9003b30105cee11b0818bd5205f55/kotlin-result/src/commonMain/kotlin/com/github/michaelbull/result/Factory.kt#L44).

Your example would go like this:

```kotlin
val value = maybeGetValue()?.toResultOr { ValueMissingError }.bind()
```

**Comment by michaelbull** [comment]
@kirillzh does that help?

**Comment by kirillzh** [comment]
To clarify, `maybeGetValue` in this example would return a `Result` with nullable value, for example `Result<String?,  SomeError>. 

I guess we can't quite use `toResultOr()` directly on the result here, bit we could chain `bind()`s: 🤔 

```kotlin
val value = maybeGetValue()
  .bind()
  .toResultOr { ValueMissingError }
  .bind()
```

**Comment by michaelbull** [comment]
Ah okay, so you want to keep it as a `Result` but turn it to an `Err` if the current `Result` is an `Ok(null)`? Is my understanding here correct?

**Comment by kirillzh** [comment]
Exactly! The original proposed API for that I mentioned...
```kotlin
val value = maybeGetValue().bind()
ensureNotNull(value) { ValueMissingError }
```

Now as I'm thinking through it, the actual API that I am looking for roughly looks like this:
```kotlin
inline fun <V, E> Result<V?, E>.ensureNotNull(
  error: (V?) -> E,
): Result<V, E> = ensure(
  predicate = { it != null },
  error = error,
).map { it as V }

inline fun <V, E> Result<V, E>.ensure(
  predicate: (V) -> Boolean,
  error: (V) -> E,
): Result<V, E> = flatMap { if (predicate(it)) Ok(it) else Err(error(it)) }
```

And so instead of using `flatMap`:
```kotlin
val value = maybeGetValue()
  .flatMap {
    when (it) {
      null -> Err(ValueMissingError)
      else -> Ok(it)
    }
  }
  .bind()
```

Can use `ensureNotNull` here:
```kotlin
val value = maybeGetValue()
  .ensureNotNull { ValueMissingError }
  .bind()
```

**Comment by michaelbull** [comment]
I wonder if we just make a `toErrorIfNull` that utilises the [`toErrorIf`](https://github.com/michaelbull/kotlin-result/blob/master/kotlin-result/src/commonMain/kotlin/com/github/michaelbull/result/Map.kt#L176) function?

**Comment by kirillzh** [comment]
@michaelbull, `toErrorIfNull` is great, thanks for adding! One more thing though, could we make it return result with non-nullable value?

Right now it's implemented as:
```kotlin
public inline fun <V, E> Result<V, E>.toErrorIfNull(error: () -> E): Result<V, E> {
```

Which returns nullable success value:
```kotlin
val account = accountRepository.getActiveAccount()
  .toErrorIfNull { AccountMissing }
  .get() // Account? <--- nullable
```

A preferred signature here would be:
```kotlin
inline fun <V, E> Result<V?, E>.toErrorIfNull(error: () -> E): Result<V, E>
```

Which would return non-nullable success value:
```kotlin
val account = accountRepository.getActiveAccount()
  .toErrorIfNull { AccountMissing }
  .get() // Account <--- non-nullable
```

**Comment by michaelbull** [comment]
@kirillzh that example signature doesn't seem to work for me:

![image](https://user-images.githubusercontent.com/3253134/229752003-58387359-5a1c-4ec0-af6d-a986edc61809.png)

**Comment by kirillzh** [comment]
`get()` is expected to be nullable here, in case if result is an error? The benefit is that `toErrorIfNull` itself returns `Result<String, Int>`.

**Comment by michaelbull** [comment]
So what is the change you are requesting?

**Comment by kirillzh** [comment]
I think it needs to change from this:
```kotlin
public inline fun <V, E> Result<V, E>.toErrorIfNull(error: () -> E): Result<V, E> {
    contract {
        callsInPlace(error, InvocationKind.AT_MOST_ONCE)
    }

    return toErrorIf(
        { it == null },
        { error() }
    )
}
```

To this:
```kotlin
public inline fun <V, E> Result<V?, E>.toErrorIfNull(error: () -> E): Result<V, E> {
  contract {
    callsInPlace(error, AT_MOST_ONCE)
  }

  return toErrorIf(
    { it == null },
    { error() }
  ).map {
    @Suppress("UNCHECKED_CAST")
    it as V
  }
}
```

**Comment by michaelbull** [comment]
Okay, I think writing it out as a `when` and not utilising `toErrorIf`/`map` will probably end up being the play here as it'll likely improve readability and potentially avoid a cast. Will give it a go for both this and the `unless` case as well.

**Comment by kirillzh** [comment]
> @michaelbull, consider this snippet:
> 
> ```kotlin
> fun provideResult(): Result<String?, Int> = Ok(null)
> 
> fun main() {
>   provideResult()
>     .toErrorIfNull { 50 }
>     .map { value ->
>       value.length // <- won't compile, value is nullable
>     }
> }
> ```
> 
> I would expect for `toErrorIfNull()` to return `Result<String, Int>` not `Result<String?, Int>`.

Addressing this in https://github.com/michaelbull/kotlin-result/pull/86
