### ISSUE TITLE
Proposal: add getErr() function to UnwrapException

### ISSUE THREAD

**Issue by mbucc** [michaelbull/kotlin-result#9]
When creating a domain entity with more than five fields (so zip is not available), the best pattern I've found goes like this:

```
data class T(val a: A, val b) {
  companion object {
    fun create(x1 : String?, x2: String?) : Result<T, DomainMessage> =
      try {
        Ok(T(
          A.create(x1).unwrap(), 
          B.create(x2).unwrap()));
      } catch (e:Exception) {
        Err(ParseError("error: ${e.message}");
      }
}   
```

What I'd like to be able to do is return the original DomainMessage from the catch block:

```
      } catch (e: UnwrapException) {
        e.getErr()
      }
```

Does this seem reasonable to you?

---- Edit: in proposed catch block, change Exception to UnwrapException

**Comment by michaelbull** [comment]
I'm not a fan of throwing exceptions just to catch them to get some information out. I think a better approach is to instead have something along these lines:

```kotlin
fun exampleA(): Result<Int, String> = TODO()
fun exampleB(): Result<Int, String> = TODO()

data class Example(
    val a: Int,
    val b: Int
)

fun runExample(): Result<Example, String> {
    val a = exampleA().getOrElse { return Err(it) }
    val b = exampleB().getOrElse { return Err(it) }
    return Ok(Example(a,b))
}
```

The only  downside is you end up recreating another `Err` in the failure state.

**Comment by mbucc** [comment]
+1

BTW, thanks for this work.  I found it after reading Scott Wlaschin's "Domain Modeling Made Functional" and have yet to run into something I cannot do.  In fact, I was inspired to write a short blog post here: http://markbucciarelli.com/posts/2020-01-04_kotlin_functional_gold_mine.html)

**Comment by Munzey** [comment]
just in case someone stumbles onto this issue, the functionality described is best captured by a [monad comprehension](https://arrow-kt.io/docs/0.10/patterns/monad_comprehensions/).
I have opened a pr to add the functionality you are looking for:
#13
